#ifndef SMPL_CONSOLE_ROS_H
#define SMPL_CONSOLE_ROS_H

#include <ros/console.h>

#define SMPL_LOG_LEVEL ROSCONSOLE_MIN_SEVERITY

#define SMPL_DEBUG                          ROS_DEBUG
#define SMPL_DEBUG_STREAM                   ROS_DEBUG_STREAM
#define SMPL_DEBUG_NAMED                    ROS_DEBUG_NAMED
#define SMPL_DEBUG_STREAM_NAMED             ROS_DEBUG_STREAM_NAMED
#define SMPL_DEBUG_COND                     ROS_DEBUG_COND
#define SMPL_DEBUG_STREAM_COND              ROS_DEBUG_STREAM_COND
#define SMPL_DEBUG_COND_NAMED               ROS_DEBUG_COND_NAMED
#define SMPL_DEBUG_STREAM_COND_NAMED        ROS_DEBUG_STREAM_COND_NAMED
#define SMPL_DEBUG_ONCE                     ROS_DEBUG_ONCE
#define SMPL_DEBUG_STREAM_ONCE              ROS_DEBUG_STREAM_ONCE
#define SMPL_DEBUG_ONCE_NAMED               ROS_DEBUG_ONCE_NAMED
#define SMPL_DEBUG_STREAM_ONCE_NAMED        ROS_DEBUG_STREAM_ONCE_NAMED
#define SMPL_DEBUG_THROTTLE                 ROS_DEBUG_THROTTLE
#define SMPL_DEBUG_STREAM_THROTTLE          ROS_DEBUG_STREAM_THROTTLE
#define SMPL_DEBUG_THROTTLE_NAMED           ROS_DEBUG_THROTTLE_NAMED
#define SMPL_DEBUG_STREAM_THROTTLE_NAMED    ROS_DEBUG_STREAM_THROTTLE_NAMED

#define SMPL_INFO                           ROS_INFO
#define SMPL_INFO_STREAM                    ROS_INFO_STREAM
#define SMPL_INFO_NAMED                     ROS_INFO_NAMED
#define SMPL_INFO_STREAM_NAMED              ROS_INFO_STREAM_NAMED
#define SMPL_INFO_COND                      ROS_INFO_COND
#define SMPL_INFO_STREAM_COND               ROS_INFO_STREAM_COND
#define SMPL_INFO_COND_NAMED                ROS_INFO_COND_NAMED
#define SMPL_INFO_STREAM_COND_NAMED         ROS_INFO_STREAM_COND_NAMED
#define SMPL_INFO_ONCE                      ROS_INFO_ONCE
#define SMPL_INFO_STREAM_ONCE               ROS_INFO_STREAM_ONCE
#define SMPL_INFO_ONCE_NAMED                ROS_INFO_ONCE_NAMED
#define SMPL_INFO_STREAM_ONCE_NAMED         ROS_INFO_STREAM_ONCE_NAMED
#define SMPL_INFO_THROTTLE                  ROS_INFO_THROTTLE
#define SMPL_INFO_STREAM_THROTTLE           ROS_INFO_STREAM_THROTTLE
#define SMPL_INFO_THROTTLE_NAMED            ROS_INFO_THROTTLE_NAMED
#define SMPL_INFO_STREAM_THROTTLE_NAMED     ROS_INFO_STREAM_THROTTLE_NAMED

#define SMPL_WARN                           ROS_WARN
#define SMPL_WARN_STREAM                    ROS_WARN_STREAM
#define SMPL_WARN_NAMED                     ROS_WARN_NAMED
#define SMPL_WARN_STREAM_NAMED              ROS_WARN_STREAM_NAMED
#define SMPL_WARN_COND                      ROS_WARN_COND
#define SMPL_WARN_STREAM_COND               ROS_WARN_STREAM_COND
#define SMPL_WARN_COND_NAMED                ROS_WARN_COND_NAMED
#define SMPL_WARN_STREAM_COND_NAMED         ROS_WARN_STREAM_COND_NAMED
#define SMPL_WARN_ONCE                      ROS_WARN_ONCE
#define SMPL_WARN_STREAM_ONCE               ROS_WARN_STREAM_ONCE
#define SMPL_WARN_ONCE_NAMED                ROS_WARN_ONCE_NAMED
#define SMPL_WARN_STREAM_ONCE_NAMED         ROS_WARN_STREAM_ONCE_NAMED
#define SMPL_WARN_THROTTLE                  ROS_WARN_THROTTLE
#define SMPL_WARN_STREAM_THROTTLE           ROS_WARN_STREAM_THROTTLE
#define SMPL_WARN_THROTTLE_NAMED            ROS_WARN_THROTTLE_NAMED
#define SMPL_WARN_STREAM_THROTTLE_NAMED     ROS_WARN_STREAM_THROTTLE_NAMED

#define SMPL_ERROR                          ROS_ERROR
#define SMPL_ERROR_STREAM                   ROS_ERROR_STREAM
#define SMPL_ERROR_NAMED                    ROS_ERROR_NAMED
#define SMPL_ERROR_STREAM_NAMED             ROS_ERROR_STREAM_NAMED
#define SMPL_ERROR_COND                     ROS_ERROR_COND
#define SMPL_ERROR_STREAM_COND              ROS_ERROR_STREAM_COND
#define SMPL_ERROR_COND_NAMED               ROS_ERROR_COND_NAMED
#define SMPL_ERROR_STREAM_COND_NAMED        ROS_ERROR_STREAM_COND_NAMED
#define SMPL_ERROR_ONCE                     ROS_ERROR_ONCE
#define SMPL_ERROR_STREAM_ONCE              ROS_ERROR_STREAM_ONCE
#define SMPL_ERROR_ONCE_NAMED               ROS_ERROR_ONCE_NAMED
#define SMPL_ERROR_STREAM_ONCE_NAMED        ROS_ERROR_STREAM_ONCE_NAMED
#define SMPL_ERROR_THROTTLE                 ROS_ERROR_THROTTLE
#define SMPL_ERROR_STREAM_THROTTLE          ROS_ERROR_STREAM_THROTTLE
#define SMPL_ERROR_THROTTLE_NAMED           ROS_ERROR_THROTTLE_NAMED
#define SMPL_ERROR_STREAM_THROTTLE_NAMED    ROS_ERROR_STREAM_THROTTLE_NAMED

#define SMPL_FATAL                          ROS_FATAL
#define SMPL_FATAL_STREAM                   ROS_FATAL_STREAM
#define SMPL_FATAL_NAMED                    ROS_FATAL_NAMED
#define SMPL_FATAL_STREAM_NAMED             ROS_FATAL_STREAM_NAMED
#define SMPL_FATAL_COND                     ROS_FATAL_COND
#define SMPL_FATAL_STREAM_COND              ROS_FATAL_STREAM_COND
#define SMPL_FATAL_COND_NAMED               ROS_FATAL_COND_NAMED
#define SMPL_FATAL_STREAM_COND_NAMED        ROS_FATAL_STREAM_COND_NAMED
#define SMPL_FATAL_ONCE                     ROS_FATAL_ONCE
#define SMPL_FATAL_STREAM_ONCE              ROS_FATAL_STREAM_ONCE
#define SMPL_FATAL_ONCE_NAMED               ROS_FATAL_ONCE_NAMED
#define SMPL_FATAL_STREAM_ONCE_NAMED        ROS_FATAL_STREAM_ONCE_NAMED
#define SMPL_FATAL_THROTTLE                 ROS_FATAL_THROTTLE
#define SMPL_FATAL_STREAM_THROTTLE          ROS_FATAL_STREAM_THROTTLE
#define SMPL_FATAL_THROTTLE_NAMED           ROS_FATAL_THROTTLE_NAMED
#define SMPL_FATAL_STREAM_THROTTLE_NAMED    ROS_FATAL_STREAM_THROTTLE_NAMED

#endif
